version: "3"
services:
  client:
    image: sgarmendia/books-client
    mem_limit: 128m
    hostname: client
  server:
    image: sgarmendia/books-server
    mem_limit: 128m
    hostname: api
  nginx:
    image: sgarmendia/books-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
