version: "3"
services:
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      context: ./nginx
    ports:
      - "3050:80"
